### ISSUE TITLE
Possibility to remove Title (white) if adding custom params

### ISSUE THREAD

**Issue by andrewsalive** [k0shk0sh/RetainedDateTimePickers#1]
https://github.com/k0shk0sh/RetainedDateTimePickers/blob/master/art/custom_theme_date.png

**Comment by k0shk0sh** [comment]
Hello @andrewsalive thanks for opening this issue, it would be good to have that passed with the 
`DateTimeBuilder`, i'll try and do it within this weekend, if you got a clue in how to do it, please do PR, i will really appreciate it. 
Thanks

**Comment by k0shk0sh** [comment]
current workaround would be to set `<item windowNoTitle>true</item>` would fix it.

**Comment by andrewsalive** [comment]
@k0shk0sh cool, all good! tnx for such a fast reply and for great library.
