### ISSUE TITLE
how to open 'advanced' date picker dialog ?

### ISSUE THREAD

**Issue by razorree** [k0shk0sh/RetainedDateTimePickers#6]
How to open this date picker dialog ?
https://github.com/k0shk0sh/RetainedDateTimePickers/blob/master/art/date_picker_portrait.png

The only one i can open from my app, is simple one, with 3 spinners (year, month, day) - no calendar view.

**Comment by k0shk0sh** [comment]
what API are you running the library at?

**Comment by razorree** [comment]
Ok. i learnt it's something with Android versions.... your sample app, running on Android 5.1 emulator (and compile/targetsdk 25) shows calendar view pickers, but my app, running on the same emulator shows simple picker with spinners...

but i still can't figure it out
