### ISSUE TITLE
How should I invoke TimePickerFragment Dialog in PreferenceFragment?

### ISSUE THREAD

**Issue by karanrajpal14** [k0shk0sh/RetainedDateTimePickers#7]
I get the following error when I try to use getChildFragmentManager() within show()

``Error:(204, 51) error: no suitable method found for show(android.app.FragmentManager,String)
method DialogFragment.show(android.support.v4.app.FragmentManager,String) is not applicable
(argument mismatch; android.app.FragmentManager cannot be converted to android.support.v4.app.FragmentManager)
method DialogFragment.show(FragmentTransaction,String) is not applicable
(argument mismatch; android.app.FragmentManager cannot be converted to FragmentTransaction)``

**Comment by k0shk0sh** [comment]
you are passing the framework fragmentManager while you should pass the supportLib v4 fragmentManager
